# Generated by Django 2.1.3 on 2019-01-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_appoved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='appoved',
            new_name='approved',
        ),
    ]
